### ISSUE TITLE
.ts extension is used for both binary and text...

### ISSUE THREAD

**Issue by ost12666** [bevry/istextorbinary#10]
This breaks the test using file extension

**Comment by balupton** [comment]
Can you provide code to reproduce this, as this should not be the case.

**Comment by ost12666** [comment]
"ts" is used for TypeScript files but also for video MPEG-TS files (https://en.wikipedia.org/wiki/MPEG_transport_stream). I am not sure what do you mean code to reproduce. Using extension to decide if this kind of file is text or binary is not possible.

**Comment by balupton** [comment]
Oh. Ok. Makes sense. I thought you meant it was in both listings. Can you send a PR to remove it from textextensions with that reasoning.

**Comment by ost12666** [comment]
Thanks!

**Comment by balupton** [comment]
I'll also do up another listing for textorbinaryextensions that has ts in it, and updates tests to make sure it doesn't say ts doesn't added back to one or the other
