### ISSUE TITLE
Reading 24 bytes possibly results in incorrect chunks

### ISSUE THREAD

**Issue by dlsgusrn7577** [bevry/istextorbinary#13]
I apologize in advance if this issue is a false alarm.

When reading 24 bytes in the middle and end of buffer (for method 'getEncodingSync'),
isn't it possible to get incorrectly chunked bytes?

For instance, let's say a file is consisted of 75 characters of '한', which is a Korean character represented as 3 bytes for utf8 encoding.
If we want to read middle 24 bytes, then
```
   chunkBegin =  Math.max(0, Math.floor(75 * 3 / 2) - chunkLength) = 88
   chunkEnd =  Math.min(75 * 3, 88 + chunkLength) = 112
```
However, since 88 is not multiple of 3, `buffer.toString(encoding, 88, 112)` will not result in the list of Korean characters '한'.

Please let me know if I am misunderstanding.
Thank you very much!

**Comment by balupton** [comment]
Seems plausible. Can you submit a PR that has a test that showcases this problem? Then you can update the PR with the fix (I guess flooring to the nearest 3 divisible) and we can do a release.

**Comment by sainthkh** [comment]
I'm currently working on this. I found error strings like:

* 12345678901234567890123Ф
* 1234567890123456789012안

It might take some time because I need a complete list of error cases.
