### ISSUE TITLE
Breaks when compiling with `@vercel/ncc`

### ISSUE THREAD

**Issue by smithki** [bevry/istextorbinary#166]
When attempting to compile a package depending on `istextorbinary` using [`@vercel/ncc`](https://github.com/vercel/ncc), the following error is raised:

```
Module not found: Error: Default condition should be last one
```

The error originates from [`enhanced-resolve`](https://github.com/webpack/enhanced-resolve), which apparently requires the `"default"` key in the `"exports": { "node": { ... } }` mapping is listed _last._

The fix should be simply to [reorder this line in `package.json`](https://github.com/bevry/istextorbinary/blob/2f4d90a9b7af6924adb136f9bcb0ea937985e3c5/package.json#L196).

**Comment by balupton** [comment]
> The fix should be simply to [reorder this line in `package.json`](https://github.com/bevry/istextorbinary/blob/2f4d90a9b7af6924adb136f9bcb0ea937985e3c5/package.json#L196).

Can you send a PR

**Comment by smithki** [comment]
Looks like this issues is no longer relevant as of [this change](https://github.com/bevry/istextorbinary/commit/9d3621e7c4726ea04fde8ea1c99ed72d32a6f9ee).
