### ISSUE TITLE
Add support to node 16.

### ISSUE THREAD

**Issue by mshima** [bevry/istextorbinary#200]
Current version fails with node 16.

It should support node >= instead of a particular version.

See https://github.com/yeoman/yo/issues/662

**Comment by scalvert** [comment]
Potential fix: https://github.com/bevry/istextorbinary/pull/201

**Comment by christianpaquin** [comment]
Is there an ETA for node 16 support?

**Comment by balupton** [comment]
End of June is the target. I have a bunch of changes in bevry/boundation that need to be released, which is our automated maintenance tool.

Please consider posting a bounty or funding my work, as it is all done for free in my spare time as a solo indie dev with zero support.

https://bevry.me/fund

**Comment by balupton** [comment]
Support is coming this week. Work has already commenced.

I'm streaming the process on Twitch:
https://twitch.tv/balupton

Please consider funding, as I'm a bootstrapped soloprenuer whose only salary is donations, hence delays.
https://bevry.me/fund

**Comment by balupton** [comment]
Support is still on the way and is still the active task (just had more sub tasks than expected). Links from prior post are still relevant, that is [progress can be followed on Twitch](https://twitch.tv/balupton) and [funded so that I get a return on this time investment](https://bevry.me/fund).

**Comment by balupton** [comment]
Bug was over in [Editions](https://github.com/bevry/editions):

https://github.com/bevry/editions/issues/235

A forced editions dependency upgrade is happening on all the Bevry packages now via [boundation](https://github.com/bevry/boundation).

Once the automated release happens in the coming hours, it should resolve this problem.

**Comment by balupton** [comment]
v5.14.0 is now out, which should resolve this problem.

---

[❤️ Please consider funding my work so things like this never happen in the first place, or when they do happen, I can afford the time to fix them speedily. ❤️](https://github.com/sponsors/balupton)
