### ISSUE TITLE
npm version 1.0.1 contains no code

### ISSUE THREAD

**Issue by omsmith** [bevry/istextorbinary#3]
It seems you forgot to build before publishing 1.0.1

Please republish with output as 1.0.2

**Comment by 44px** [comment]
+1

**Comment by petermetz** [comment]
+1

**Comment by babaev** [comment]
+1 plz fix asap

**Comment by radekk** [comment]
+1

**Comment by eswak** [comment]
:+1:

**Comment by Alexgalinier** [comment]
+1

**Comment by oskarwrobel** [comment]
+1

**Comment by tijee** [comment]
:+1:

**Comment by nexus-uw** [comment]
yet another +1

**Comment by robbiemccorkell** [comment]
And another +1

**Comment by omsmith** [comment]
@balupton

**Comment by lazd** [comment]
@bevry already getting PRs to hardcode old version numbers, can we fix this today?

**Comment by bawigga** [comment]
+1

**Comment by Toilal** [comment]
:+1: ;à

**Comment by tempoc** [comment]
+1

**Comment by AndrewBarba** [comment]
+1

**Comment by varya** [comment]
+1. Docpad is broken because of it

**Comment by nickradford** [comment]
Temporary fix for all of us, if you just `npm install istextorbinary@1.0.0` until the author has a chance to republish, node should find it.

**Comment by mikeumus** [comment]
Pretty sure @balupton's asleep right now. :sleeping::zzz: 

:hankey: :heavy_plus_sign:  :fire:

**Comment by balupton** [comment]
:O 

Fixing now!

**Comment by balupton** [comment]
Fixed everyone. So sorry about this. Turns out it was due to upgrading the base files, and leaving out the new required `cakeConfiguration` config in `package.json`.

Surprised `cake prepublish` didn't pick this up, maybe it no longer does tests. If so, it should certainly do.

**Comment by eswak** [comment]
:hand: thanks !

**Comment by omsmith** [comment]
Great, thanks!

**Comment by varya** [comment]
Thanks!
