### ISSUE TITLE
Does this specifically check for utf8 text?

### ISSUE THREAD

**Issue by tolmasky** [bevry/istextorbinary#6]
Just wanted some clarification of what "isText" meant exactly. for example, isText(new Buffer("abc", 'utf-16le")) returns false. Can I thus be sure if isText is true then the contents is utf8 text, or are there cases where it might be something else?

**Comment by balupton** [comment]
From my memory, anything above UTF8 is more or less identical to binary. So only UTF8 text is supported here, happy to accept a PR if someone figures out how to do other text types.
