### ISSUE TITLE
5.3.0 update ESLint dependency interferes with create-react-app 

### ISSUE THREAD

**Issue by welljsjs** [bevry/istextorbinary#62]
Starting with v5.3.0, a bunch of dependencies were added to package.json that seem like they should be dev-dependencies only.<br>
They're currently installed twice as a regular dependency and as a dev dependency. <br>
Is there a reason for that?<br>

For reference: 
eslint@7.3.0 installed as a dependency: https://github.com/bevry/istextorbinary/commit/95c929608785694c678160ddbd0c34ee0c7cb4f7#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R165
..and as dev-dependency: https://github.com/bevry/istextorbinary/commit/95c929608785694c678160ddbd0c34ee0c7cb4f7#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R184

This leads to a severe warning message when using create-react-app: 

```
There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to fix locally.

The react-scripts package provided by Create React App requires a dependency:

  "eslint": "^6.6.0"

Don't try to install it manually: your package manager does it automatically.
However, a different version of eslint was detected higher up in the tree:

  /<project_path>/node_modules/eslint (version: 7.3.0) 
```

Could you please remove eslint@7.3.0 from the module's depencies and install it as a dev-dependency only? This is causing us a little headache at the moment.

**Comment by balupton** [comment]
yeah, they are meant to be dev dependencies, will figure it out now

**Comment by balupton** [comment]
found the cause, figuring out a fix now

**Comment by balupton** [comment]
found the culprit

https://github.com/bevry/make-deno-edition/commit/d7383900c037314557caf0986d011ef6fbbf314a#diff-21e9ddd93162651bd36f6e5bbfca8460L443

fixing all the bevry packages now

**Comment by balupton** [comment]
let me know if v5.4.0 releasing now https://travis-ci.com/github/bevry/istextorbinary/jobs/351794075 fixes it

**Comment by welljsjs** [comment]
It does, thank you!
