### ISSUE TITLE
`istextorbinary.isText` returned a wrong result

### ISSUE THREAD

**Issue by gucong3000** [bevry/istextorbinary#9]
```js
#!/usr/bin/env node
'use strict';
const fs = require('fs');
const path = require('path');
const istextorbinary = require('istextorbinary');
const filePath = path.resolve('index.wxml');
istextorbinary.isText(filePath, fs.readFileSync(filePath), console.log);
```

I got `false` as result. but here is contents of `src/components/Template/Auth/index.wxml`:
[index.zip](https://github.com/bevry/istextorbinary/files/2248159/index.zip)

```xml
<template name="auth">
  <view class="auth-wrap">
    <view class="auth-logo box box-tb box-align-center">
      <image src="../../../images/link-logo.png" class="auth-logo-img"></image>
      <text class="auth-company-name fs-32">街电科技</text>
    </view>
    <view class="auth-desc box box-tb">
      <text class="fs-28 auth-desc-title">登录后开发者将获得以下权限</text>
      <text class="fs-26 auth-desc-detail box box-lr box-align-center">获取你的公开信息（昵称、头像等）</text>
    </view>
    <auth-button
      btn-open-type="{{btnOpenType}}"
      custom-data="{{customData}}"
      data-custom-data="{{customData}}"
      auth-btn-class="auth-page-class"
      bind:auth="onClickAuth">确认登录</auth-button>
    <view class="auth-protocol fs-24">
      登录即表示同意 <text bindtap="jumpToTerms"  data-url="https://appstatic.ankerjiedian.com/app/dist/term.html" class="auth-terms">《街电用户协议》</text>
    </view>
  </view>
</template>
```

**Comment by balupton** [comment]
Interesting. Is that text UTF8 or UTF16 or something else?

**Comment by gucong3000** [comment]
> Is that text UTF8 or UTF16 or something else?

I was update this file to => https://github.com/bevry/istextorbinary/files/2248159/index.zip

**Comment by balupton** [comment]
Ah right, it is the `登录即表示同意` characters that are throwing it off. I'll add wxml to https://github.com/bevry/textextensions to fix this.

**Comment by LvChengbin** [comment]
I encountered the same issue while detecting a file with Chinese characters.
I found that you tried to split the buffer and checked every part of it, but while Chinese characters appears, it might be split into pieces and then the decoder will get some invalid sequence of bytes, and it will replace that sequence with U+FFFD(65533), the condition which you are using it for determining if the source is  binary or not.

**Comment by balupton** [comment]
@LvChengbin the algorithm's considerations are explained in the README. The only way to work around this would be to provide the file extension, and ensure the file extension is inside https://github.com/bevry/textextensions
